config/routes.rb
PayMonkey::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :payments
  resources :user_mailers

  match '/about', to: 'static_pages#about'

  match '/payments/:id/editnr', to: 'payments#editnr', as: 'editnr', via: 'get'
  match '/payments/nr/:id', to: 'payments#updatenr', via: 'put'

  root :to => 'static_pages#home'
  

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  attr_accessible :amount, :description, :email, :frequency, :paid, :user_id
  belongs_to :user

  validates :email, :presence => true, :format => { :with => /.+@.+\..+/i }
  validates :amount, :presence => true, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0}
  validates :description, :presence => true, :length => { :maximum => 40 }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  
  
  before_filter :authenticate_user!

  #def correct_user
  #  user = Goal.find(params[:id]).user if params[:id]
  #  redirect_to user_path(current_user) and return unless current_user?(user)
  #end
  #http://stackoverflow.com/questions/6050670/preventing-other-signed-in-users-from-accessing-edit-page?rq=1
  
  def index

    @payments_all = Payment.all
    @payments_current = current_user.payments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments_all }
      format.json { render json: @payments_current }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = current_user.payments.find(params[:id])  #*** THIS WILL GIVE ERROR FOR SHOWING MONEY YOU OWE
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    if current_user.pay_method == nil  # If user has not yet entered in a payment method (b/c new to the site)
      # @skip_to_new_payment = true
      redirect_to edit_user_mailer_url(current_user), :flash => { notice: 'Before creating a new payment, please let us know how you would like to be paid back' }
      return
    end
    # Use "build" rather than "new" for association current_user.payments

    @payment = current_user.payments.build
    @preview = false

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = current_user.payments.find(params[:id])
  end

  # GET /payments/1/edit ... editing for non-registered users
  def editnr 
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create

    if params[:commit] == "Create" #If create button is pushed
      @payment = current_user.payments.build(params[:payment])
      
      #if payee does not exist as user, then create new user with Token
      unless User.find_by_email(params[:payment][:email].downcase)  
        u = User.new({:email => params[:payment][:email].downcase, :password => nil, :password_confirmation => nil, :not_registered => 1 })
        u.skip_confirmation!
        u.save(:validate => false)  #skip validation
        u.reset_authentication_token!
      end

      respond_to do |format|
        if @payment.save
          
          # Tell the UserMailer to send a welcome Email after save
          UserMailers.welcome_email(@payment).deliver

          format.html { redirect_to payments_url, :flash => { notice: 'First email payment reminder has been sent.' } }
          format.json { render json: @payment, status: :created, location: @payment }
        else
          format.html { render action: "new" }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    else #if preview button is pushed
      @payment = current_user.payments.build(params[:payment])
      @preview = true
      render :action => "new"
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = current_user.payments.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to payments_url, :flash => { :success => "Payment was successfully updated." } }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def updatenr
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to payments_url, :flash => { :success => "Payment was successfully updated." } }
        format.json { head :no_content }
        if @payment.paid == "paid"
          UserMailers.paid_email(@payment).deliver
        end
      else
        format.html { render action: "editnr" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = current_user.payments.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, :flash => { :success => "Payment was successfully deleted." }  }
      format.json { head :no_content }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    <div class="field">
      <div class="control-group">
        <%= f.label :email, "Email of person who owes you $$$", class: "control-label" %><br />
        <div class="controls">
          
          <!-- Old email input was text_field; code works fine when using the following code: -->
          <%#= f.text_field :email %>
          <%#= f.collection_select :email, current_user.payments.select(:email).uniq, :email, :email, {:include_blank => "Please select"} %> 

          <%=f.select(:email, [ [ 'Add new email address...', 'new' ] ] + current_user.payments.collect(&:email).uniq, {:include_blank => 'Please select'}) %>
        </div>
      </div>
    </div>

    <div class="control-group">
      <div class="field">
        <%= f.label :email, "Enter new email address", class: "control-label", id: 'add_email_label', style: 'display:none;' %><br />
        <div class="controls">
          <%= f.text_field :email, id: 'add_email_field', style: 'display:none;' %>
        </div>
      </div>
    </div>  

    <div class="control-group">
      <div class="field">
        <div class="input-prepend">
          <%= f.label :amount, "Amount owed", class: "control-label" %><br />
          <div class="controls">
            <span class="add-on">$</span>
          
            <%= f.text_field :amount, class: "Span2", id: "prependedInput" %>
          </div>
        </div>
      </div>
    </div>

    <div class="control-group">
      <div class="field">
        <%= f.label :frequency, "Send reminder emails", class: "control-label" %><br />
        <div class="controls">
          <%= f.select :frequency, [['Biweekly', 'biweekly'],['Weekly', 'weekly'], ['Daily', 'daily'], ['No reminder', 'no_reminder']], {:include_blank => 'Please select'} %>
        </div>
      </div>
    </div>
    
    <div class="control-group">
      <div class="field">
        <%= f.label :description, "Description of what is owed", class: "control-label" %><br />
        <div class="controls">
          <%= f.text_field :description %>
        </div>
      </div>
    </div>  

    <div class="field">
      <%= f.hidden_field :paid, :value => "pending" %>
    </div>
    <div class="control-group">
      <div class="actions">
        <div class="controls">  
          <%= f.submit %>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/payments/_form_loaner.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    
    <%# only render form if not in preview mode; otherwise, include @payment params in hidden fields %>
    <% if @preview != true %>

      <div class="control-group">
        

        
        <div class="field">
          <%= f.label :email, "Email of person who owes you $$$", class: "control-label" %><br />
          <div class="controls">
            
            <!-- Old email input was text_field; code works fine when using the following code: -->
            <%#= f.text_field :email %>
            <%#= f.collection_select :email, current_user.payments.select(:email).uniq, :email, :email, {:include_blank => "Please select"} %> 

            <%=f.select(:email, [ [ 'Add new email address...', 'new' ] ] + current_user.payments.collect(&:email).uniq, {:prompt => true}) %>
          </div>
        </div>
      </div>

      <div class="control-group">
        <div class="field">
          <%= f.label :email, "Enter new email address", class: "control-label", id: 'add_email_label', style: 'display:none;' %><br />
          <div class="controls">
            <%= f.text_field :email, id: 'add_email_field', style: 'display:none;' %>
          </div>
        </div>
      </div>  

      <div class="control-group">
        <div class="field">
          <div class="input-prepend">
            <%= f.label :amount, "Amount owed", class: "control-label" %><br />
            <div class="controls">
              <span class="add-on">$</span>
            
              <%= f.text_field :amount, class: "Span2", id: "prependedInput" %>
            </div>
          </div>
        </div>
      </div>

      <!--div class="control-group">
        <div class="field">
          <%#= f.label :frequency, "Send reminder emails", class: "control-label" %><br />
          <div class="controls">
            <%#= f.select :frequency, [['Biweekly', 'biweekly'],['Weekly', 'weekly'], ['Daily', 'daily'], ['No reminder', 'no_reminder']], {:include_blank => 'Please select'} %>
          </div>
        </div>
      </div> -->
      
      <div class="control-group">
        <div class="field">
          <%= f.label :description, "Description of what is owed", class: "control-label" %><br />
          <div class="controls">
            <%= f.text_field :description %>
          </div>
        </div>
      </div>
      <div class="field">
        <%= f.hidden_field :frequency, :value => "weekly" %>
      </div>

      <div class="field">
        <%= f.hidden_field :paid, :value => "pending" %>
      </div>
    <% else %>

      <div class="field">
        <%= f.hidden_field :email, :value => @payment.email %>
      </div>

      <div class="field">
        <%= f.hidden_field :description, :value => @payment.description %>
      </div>

      <div class="field">
        <%= f.hidden_field :amount, :value => @payment.amount %>
      </div>

      <div class="field">
        <%= f.hidden_field :frequency, :value => @payment.frequency %>
      </div>

      <div class="field">
        <%= f.hidden_field :paid, :value => @payment.paid %>
      </div>

    <% end %>



    <div class="control-group">
      <div class="actions">
        <div class="controls">  
          <%= f.submit "Preview" if @preview != true %>
          <%= f.submit "Create" if @preview == true %>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/payments/_form_payer.html.erb
<%= form_for @payment, :url => { :action => "updatenr" } do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <b>Owe Money To:</b>
  <%= @payment.email %>
</p>

<p>
  <b>Description:</b>
  <%= @payment.description.capitalize %>
</p>

<p>
  <b>Amount Owed:</b>
  <%= number_to_currency(@payment.amount) %>
</p>



  <form class="form-horizontal">


    <div class="control-group">
      <div class="field">
        <%= f.label :paid, "Paid Status", class: "control-label" %><br />
        <div class="controls">
          <%= f.select :paid, [ ['Pending', 'pending'],['Paid', 'paid'] ], {:include_blank => 'Please select'} %>
        </div>
      </div>
    </div>
    
    <div class="control-group">
      <div class="actions">
        <div class="controls">  
          <%= f.submit :confirm => "Are you sure you want to change status?  If you change status to paid, we will remove the payment from your queue and you will no longer get emailed reminders." %>
        </div>
      </div>
    </div>
  </form>
<% end %>

app/views/payments/_index_loaner.html.erb
<h1>Payments owed to you</h1>

<% if @payments_current.empty? %>
  You don't currently have any payments owed to you.  Add a payment by clicking "New Payment" below
  <br/><br/>
<% else %>
  
  <table class="table table-striped table-bordered table-condensed">

      <tr>
        <th>Owed Money By</th>
        <th>Description</th>
        <th>Amount Owed</th>
        <th>Send Reminder Emails</th>
        <th>Paid Status</th>
        <th>Created</th>
        <th></th>
        <!--<th></th>-->
      </tr>


  <% @payments_current.sort { |a, b| a.email <=> b.email }.each do |payment| %>
    <tr>
      <td><%= payment.email %></td>
      <td><%= word_wrap(payment.description.capitalize, :line_width => 8) %></td>
      <td><%= number_to_currency(payment.amount) %></td>
      <td><%= payment.frequency.capitalize %></td>
      <td><%= payment.paid.capitalize %></td>
      <td><%= payment.created_at.strftime("%b %d %Y") %></td>
      <!--<td><%#= link_to 'Show', payment %></td>-->
      <td>
        <% if payment.paid != "paid" %>
          <%= link_to 'Edit', edit_payment_path(payment) %> | 
          <%= link_to 'Cancel', payment, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= link_to 'Remove', payment, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>


<%= link_to 'New Payment', new_payment_path, class: "btn btn-primary" %>

<%= link_to 'Set Payment Options', edit_user_mailer_path(current_user), class: "btn btn-primary" %><br />

app/views/payments/_index_payer.html.erb
<h1>Payments owed to others</h1>

<% if current_user.not_registered == 1 %>
  <br>
  Hello there, I see that you're not a registered user at PayMonkee, so let me give you a quick tour.  Just below this note you'll see a list of payments that you owe to your friends.  Once you pay back your friend, simply click "Edit status" and update the status to "Paid."  This will alert your friend that you have paid, remove the payment from your feed, and stop the email reminders we have been sending you.  
  <br><br>
  Ok, now back to my banana eating!
  <br>
  <br>
<% end %>

<% @count = 0 %>
<% @payments_all.sort { |a, b| a.user.email <=> b.user.email }.each do |payment| %>
  <% if (payment.email == current_user.email) && (payment.paid != 'paid') %>
    <% @count += 1 %>
  <% end %>
<% end %>
<% if @count > 0 %>

  <table class="table table-striped table-bordered table-condensed">
    <tr>
      <!--th>Borrower</th-->
      <th>You Owe Money To</th>
      <th>Description</th>
      <th>Amount Owed</th>
      <th>Paid Status</th>
      <th></th>
    </tr>

    <% @payments_all.sort { |a, b| a.user.email <=> b.user.email }.each do |payment| %>
      <tr>
      <% if (payment.email == current_user.email) && (payment.paid != 'paid') %>
        <!--td><%#= payment.email %></td-->
        <td><%= payment.user.email %></td>
        <td><%= word_wrap(payment.description, :line_width => 8) %></td>
        <td><%= number_to_currency(payment.amount) %></td>
        <td><%= payment.paid.capitalize %></td>
        <!--<td><%#= link_to 'Show', payment %></td>-->
        <td><%= link_to 'Edit status', editnr_path(payment) %></td>
      <% end %>
      </tr>
    <% end %>
  </table>
  
<% else %>
  You don't currently owe any payments to others
<% end %>



<br />

app/views/payments/edit.html.erb
<% provide(:title, 'Edit') %>
    <div class="container-narrow">
        <%= render :partial => 'layouts/header', :locals => { :active => 'Payments' }  %>

<h1>Editing payment</h1>

<%= render 'form_loaner' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

<%= render 'layouts/footer' %>
    </div>

app/views/payments/editnr.html.erb
<% provide(:title, 'Edit') %>
    <div class="container-narrow">
        <%= render :partial => 'layouts/header', :locals => { :active => 'Payments' }  %>

<h1>Editing payment</h1>

<%= render 'form_payer' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

<%= render 'layouts/footer' %>
    </div>

app/views/payments/index.html.erb
<% provide(:title, 'Index') %>
    <div class="container-narrow">
        <%= render :partial => 'layouts/header', :locals => { :active => 'Payments' }  %>



<%= render 'layouts/render_messages' %>


<% if current_user.not_registered != 1 %>
	<%= render 'payments/index_loaner' %>
	<br/>
	<hr>
	<%= render 'payments/index_payer' %>
<% else %>
	<%= render 'payments/index_payer' %>
	<br/>
	<hr>
	<h1>Payments owed to you</h1>
	<p>You cannot track payments owed to you, because you are not a registered user.  But fear not, you can become one for free in a few seconds.  To track payments that your friends owe you and automatically send them reminders, sign up below.</p>
	<%= link_to 'Sign Up Now', edit_user_registration_path, class: "btn btn-primary" %>

<% end %>



<%= render 'layouts/footer' %>
    </div>

app/views/payments/new.html.erb
<% provide(:title, 'New') %>

<div class="container-narrow">
    <%= render :partial => 'layouts/header', :locals => { :active => 'Payments' }  %>

	<% if @preview == true %>
    	<h1>Preview email</h1>
    	<p><b>Your PayMonkee reminder is <u>not complete</u> until you confirm submission below.  The following email will be sent initially and weekly to your friend.  Please confirm by clicking create below.</b></p>
    	<div id = "email_preview">
		  <%= render partial: 'layouts/email_body', locals: { pay_method: @payment.user.pay_method, pay_description: @payment.user.pay_desc, email_instructions: @payment.user.email_instructions, payer_email: @payment.email, loaner_email: @payment.user.email, payment_description: @payment.description, payment_amount: @payment.amount, payment_frequency: @payment.frequency, mailer_type: 'single_payment', url_override: true } %>

    	</div>
    <% end %>

    <% if @preview != true %>
        <hr>
        <h1>New payment</h1>
    <% end %>

    <%= render 'form_loaner' %>


	<%= link_to 'Back', payments_path %>

	<%= render 'layouts/footer' %>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @payment.email %>
</p>

<p>
  <b>Description:</b>
  <%= @payment.description %>
</p>

<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>

<p>
  <b>Frequency:</b>
  <%= @payment.frequency %>
</p>

<p>
  <b>Paid:</b>
  <%= @payment.paid %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>