config/routes.rb
PayMonkey::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :payments
  resources :user_mailers

  match '/about', to: 'static_pages#about'

  match '/payments/:id/editnr', to: 'payments#editnr', as: 'editnr', via: 'get'
  match '/payments/nr/:id', to: 'payments#updatenr', via: 'put'

  root :to => 'static_pages#home'
  

end

app/views/layouts/_email_body.html.erb
    <p>
      Hello, <%= payer_email %>!  This is PayMonkee, your friendly neighborhood loan shark :)<br/>
    </p>
    <p>
      <%= loaner_email %> recently lent you some money and has signed you up for a PayMonkee reminder.  Specifically, you owe

      <% if mailer_type == 'single_payment' %>
        <%= number_to_currency(payment_amount) %> for <%= payment_description.downcase %>.
      <% else %>
        :<br/><ul>
          <% @all_payments.each do |indv_payment| %>
            <li><%= number_to_currency(indv_payment.amount) %> for <%= indv_payment.description.downcase %></li>
          <% end %>
        </ul>
      <% end %>

    </p>
    <p>
      <% if defined?(pay_method) && pay_method == "paypal" %>
        Please send your payment via paypal to the address <%= pay_description %>.  
      <% end %>

      <% if defined?(pay_method) && pay_method == "mail_check" %>
        Please send your payment by mailing a check to the address <%= pay_description %>.  
      <% end %>

        We'll send you weekly reminders so you don't forget.  Once you have paid back <%= loaner_email %>, follow 
        
        <% if defined?(url_override) && url_override == true %>
          this link 
        <% else %>
          <%= link_to 'this link', @url %>
        <% end %>
        
        to confirm and stop receiving these reminders.<br/>
    </p>
    <% if email_instructions != nil && email_instructions != "" %>
      <p>Your friend asked that we pass along some additional comments:  <%= email_instructions %></p>
    <% end %>
    <p>Thanks and have a great day!</p>

    <!--a name="text_email"></a-->

app/views/layouts/_email_body.text.erb
Hello, <%= payer_email %>!  This is PayMonkee, your friendly neighborhood loan shark :)

<%= loaner_email %> recently lent you some money and has signed you up for a PayMonkee reminder.  Specifically, you owe
<% if mailer_type == 'single_payment' %>
  <%= number_to_currency(payment_amount) %> for <%= payment_description.downcase %>.
<% else %>
:

  <% @all_payments.each do |indv_payment| %>
    * <%= number_to_currency(indv_payment.amount) %> for <%= indv_payment.description.downcase %>
  <% end %>
<% end %>

<% if defined?(pay_method) && pay_method == "paypal" %>
  Please send your payment via paypal to the address <%= pay_description %>.  
<% end %>

<% if defined?(pay_method) && pay_method == "mail_check" %>
  Please send your payment by mailing a check to the address <%= pay_description %>.  
<% end %>

We'll send you weekly reminders so you don't forget.  Once you have paid back <%= loaner_email %>, follow 
<% if defined?(url_override) && url_override == true %>
  this link to confirm and stop receiving these reminders.
<% else %>
  this link to confirm and stop receiving these reminders: <%= @url %>
<% end %>

<% if email_instructions != nil && email_instructions != "" %>
  Your friend asked that we pass along some additional comments:  <%= email_instructions %></p>
<% end %>

Thanks and have a great day!

app/views/layouts/_email_footer.html.erb
  <hr>
    <p>Get a free account at PayMonkee to get your friends to pay back money they owe you.  <%= link_to 'Sign up now!', new_user_registration_url %></p>
    <p>To unsubscribe from these messages, please send an email to support@paymonkee.com with your request.</p>

app/views/layouts/_email_footer.text.erb
--------------------------------------------------
Get a free account at PayMonkee to get your friends to pay back money they owe you.  Sign up now at:  <%= new_user_registration_url %>

To unsubscribe from these messages, please send an email to support@paymonkee.com with your request.

app/views/layouts/_footer.html.erb
<hr>
<div class="footer">
	
	<p>
		© PayMonkee 2013 | 
		<%= mail_to "support@paymonkee.com", "Contact Us" %>
	</p>
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41910528-1', 'paymonkee.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div class="masthead">
	<ul class="nav nav-pills pull-right">
		<% if user_signed_in? %>
			<li <% if active == 'Payments' %> class="active" <% end %> >
				<%= link_to "Payments", payments_path %> 
			</li>

			<li <% if active == 'Edit account' %> class="active" <% end %> >
				<%= link_to "Edit Account", edit_user_registration_path %> 
			</li>

			<li <% if active == 'Logout' %> class="active" <% end %> >
				<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
			</li>
		<% else %>
			<li <% if active == 'Home' %> class="active" <% end %> >
				<%= link_to "Home", root_path %>
			</li>
			<li <% if active == 'About' %> class="active" <% end %> >
				<%= link_to "About", about_path %>
			</li>
			<li <% if active == 'Sign in' %> class="active" <% end %> >
				<%= link_to "Sign In", new_user_session_path %>
			</li>

			<li <% if active == 'Sign up' %> class="active" <% end %> >
				<%= link_to "Sign up now!", new_user_registration_path %>
			</li>

		<% end %>

		<% if user_signed_in? %>
			
			<p align="right">Logged in as <%= current_user.email %></p>
		<% end %>	
	</ul>
	<h3 class="muted">
		PayMonkee
		<%= image_tag "monkey.jpg", :size => '35x35', class: "img-rounded" %>

	</h3>

</div>	
<br>
<hr>

app/views/layouts/_header2.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#" name="top"><%= image_tag "monkey.jpg", :size => '15x15', class: "img-rounded" %> PayMonkee</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">Home</a></li>
					<li class="divider-vertical"></li>
					<li class="active"><a href="#">About</a></li>
					<li class="divider-vertical"></li>
				</ul>
				<div class="btn-group pull-right">
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-user"></i> Sign In <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
						<li class="divider"></li>
						<li><a href="#"><i class="icon-share"></i> Logout</a></li>
					</ul>
				</div>
			</div>
			<!--/.nav-collapse -->
		</div>
		<!--/.container-fluid -->
	</div>
	<!--/.navbar-inner -->
</div>
<!--/.navbar -->

app/views/layouts/_render_messages.html.erb
<%# if not @messages_rendered -%>
 <%# if flash[:error] -%>
    <!--p class='alert alert-error'><%#=h flash[:error] %></p>
  <%# end -%>
  <%# if flash[:notice] -%>
    <p class='alert'><%#=h flash[:notice] %></p>
  <%# end -%>
   <%# if flash[:success] -%>
    <p class='alert alert-success'><%#=h flash[:success] %></p>
  <%# end -%>
<%# end -%>
<%# @messages_rendered = true -%> 
-->

<% if not @messages_rendered %>
	<% [:notice, :error, :alert, :success].each do |level| %>
	  <% unless flash[level].blank? %>
	    <div class="<%= flash_class(level) %>">
	      <%= content_tag :span, flash[level] %>
	    </div>
	  <% end %>
	<% end %>
<% end %>
<% @messages_rendered = true %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PayMonkee | <%= yield(:title) %></title>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js" type="text/javascript" charset="UTF-8"></script>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

 
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
      </script>
    <![endif]-->

</head>
<body>

  
  <%= render 'layouts/render_messages' %>


	<%= yield %>

  <% if Rails.env.production? %> <%= render 'layouts/ga' %> <% end %> 

</body>
</html>